project:
  type: book

book:
  title: "The Microbiology Galaxy Lab"
  description: A community-driven gateway to tools, workflows, and training for reproducible and FAIR analysis of microbial data
  sidebar: 
    background: "transparent"
    logo: static/microgalaxy-logo.png
    search: true
  chapters:
    - href: index.qmd
      text: Home
    - qmd/publications.qmd
    - qmd/survey.qmd
    - qmd/tools.qmd
    - qmd/workflows.qmd
    - qmd/tutorials.qmd
  page-footer: 
    border: true
    background: "#ebebeb"
    left: |
      This page is built with [**Quarto**](https://quarto.org/) and is licensed under the [**MIT License**](https://opensource.org/license/mit)
    right: |
      © Copyright 2025 The Microbiology Galaxy Lab.

format:
  html:
    theme:
      light: default
    fig-format: svg
    code-fold: true
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#72876d"
    # css: sass/custom.scss
    backgroundcolor: "#F5F5F5"
knitr:
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }

execute:
  freeze: auto