---
title: "microGalaxy 2025 Paper"
---

::: {.callout-warning}
## Warning

The current version of this book is a work in progress. Any content should not be considered final at this stage.
:::

# Preface {.unnumbered}

*TOADD*

### Who is this for? {.unnumbered}

*TOADD*

### Why? {.unnumbered}

*TOADD*

## Running the code yourself {.unnumbered}

### Installation {.unnumbered}

The website is built with [Quarto](https://quarto.org/). To run the book locally, you need to [install Quarto](https://quarto.org/docs/get-started/).

Once installed launch a terminal session and run: 

```bash
quarto render
quarto preview
```

*TODO: add any relevant R/Python libraries that need to be installed*

### Data {.unnumbered}

*TOADD*

## Contributing {.unnumbered}

Contributions are welcome! You can participate by opening an issue on the GitHub repository or submitting a pull request (PR). To create a new PR, follow these steps:

1. Fork the main branch.
2. Make your contributions (refer to the Quarto Guide if needed):
    - Add a new `.qmd` file to the `qmd` folder.
    - Update an existing `.qmd` file.
    - *... add any other necessary improvements.*
3. Run a preview of your instance to see the relevant changes.
4. Open a draft PR and resolve any conflicts.
5. When ready, mark the PR as **Ready for Review**.

## Credit {.unnumbered}

*TOADD*